/**
 * HTML email template for the PNIP digest.
 *
 * Per §45, "The HTML template is responsible only for presentation. Content
 * must originate exclusively from Markdown." So this module takes pre-rendered
 * HTML body content (produced by the Markdown renderer) and wraps it with
 * the email chrome: header, optional notebook/podcast links (§9 supplies
 * these from M9/M10 — until then the links are placeholders), sources
 * appendix, and a footer.
 *
 * The output is a complete, standalone HTML document with inline styles
 * suitable for email clients that strip <style> tags.
 */

export interface EmailTemplateInput {
  publicationDate: string;
  title: string;
  renderedHtmlBody: string;
  notebookUrl?: string | null;
  podcastUrl?: string | null;
  editionId: string;
}

export interface EmailTemplate {
  subject: string;
  html: string;
  text: string;
}

export function buildEmailTemplate(input: EmailTemplateInput): EmailTemplate {
  const subject = `Daily Digest — ${input.publicationDate}`;
  const notebookLink = input.notebookUrl ?? null;
  const podcastLink = input.podcastUrl ?? null;
  const supplementaryLinks: string[] = [];
  if (notebookLink) {
    supplementaryLinks.push(
      `<li><a href="${escapeAttr(notebookLink)}" rel="noopener noreferrer">Discuss this Edition in NotebookLM</a></li>`,
    );
  }
  if (podcastLink) {
    supplementaryLinks.push(
      `<li><a href="${escapeAttr(podcastLink)}" rel="noopener noreferrer">Listen to today&rsquo;s audio digest</a></li>`,
    );
  }

  const supplementarySection =
    supplementaryLinks.length > 0
      ? `<section>
  <h2>Talk &amp; Listen</h2>
  <ul>
    ${supplementaryLinks.join("\n    ")}
  </ul>
</section>`
      : "";

  const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="x-pnip-edition" content="${escapeAttr(input.editionId)}">
<title>${escapeHtml(input.title)}</title>
</head>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,'Helvetica Neue',Arial,sans-serif;color:#1f2933;line-height:1.55;">
<table role="presentation" cellpadding="0" cellspacing="0" border="0" width="100%" style="background:#f4f4f5;padding:24px 0;">
  <tr>
    <td align="center">
      <table role="presentation" cellpadding="0" cellspacing="0" border="0" width="600" style="max-width:600px;background:#ffffff;border-radius:8px;overflow:hidden;border:1px solid #e5e7eb;">
        <tr>
          <td style="padding:24px 32px;border-bottom:1px solid #e5e7eb;">
            <h1 style="margin:0;font-size:20px;line-height:1.3;color:#0f172a;">${escapeHtml(input.title)}</h1>
            <p style="margin:6px 0 0;color:#475569;font-size:14px;">Publication date: <strong>${escapeHtml(input.publicationDate)}</strong></p>
          </td>
        </tr>
        <tr>
          <td style="padding:24px 32px;">
${input.renderedHtmlBody}
${supplementarySection}
          </td>
        </tr>
        <tr>
          <td style="padding:18px 32px;border-top:1px solid #e5e7eb;background:#f8fafc;color:#64748b;font-size:12px;">
            <p style="margin:0 0 6px;">This is a transient delivery. The canonical Markdown digest is the permanent archive for Edition <code style="font-family:ui-monospace,SFMono-Regular,Menlo,monospace;background:#e2e8f0;border-radius:3px;padding:1px 4px;">${escapeHtml(input.editionId)}</code>.</p>
            <p style="margin:0;">Generated by <strong>PNIP</strong> &middot; Resend delivery &middot; <a href="#" style="color:#475569;text-decoration:underline;">manage notifications</a></p>
          </td>
        </tr>
      </table>
    </td>
  </tr>
</table>
</body>
</html>
`;

  const text = [
    `${input.title}`,
    `Publication date: ${input.publicationDate}`,
    "",
    input.renderedHtmlBody
      .replace(/<style[\s\S]*?<\/style>/g, "")
      .replace(/<[^>]+>/g, "")
      .replace(/\s+\n/g, "\n")
      .trim(),
    "",
    notebookLink ? `Discuss this Edition in NotebookLM: ${notebookLink}` : null,
    podcastLink ? `Listen to today's audio digest: ${podcastLink}` : null,
    "",
    `This is a transient delivery. The canonical Markdown digest is the`,
    `permanent archive for Edition ${input.editionId}.`,
    `Generated by PNIP.`,
  ]
    .filter((line) => line !== null)
    .join("\n")
    .replace(/\n{3,}/g, "\n\n");

  return { subject, html, text };
}

const HTML_ESCAPES: Record<string, string> = {
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;",
};

function escapeHtml(input: string): string {
  return input.replace(/[&<>"']/g, (ch) => HTML_ESCAPES[ch] ?? ch);
}

function escapeAttr(input: string): string {
  return escapeHtml(input);
}
